runtime: nodejs16

beta_settings:
  cloud_sql_instances: "test-api-407303:asia-southeast2:users"

env_variables:
  DB_HOST: "34.101.143.128"
  DB_USER: "root"
  DB_PASSWORD: "capstone123"
  DB_NAME: "phisheye"
