runtime: nodejs16

beta_settings:
  cloud_sql_instances: "api-phisheye:us-central1:myinstance"

env_variables:
  DB_HOST: "34.27.42.51"
  DB_USER: "root"
  DB_PASSWORD: "phisheye123"
  DB_NAME: "phisheye"
